export const subComprarTema = [
  "VER TODOS LOS TEMAS",
  "Architecture",
  "Batman",
  "BrickHeadz",
  "Brick Sketches",
  "City",
  "Classic",
  "Creator 3in1",
  "Creator Expert",
  "DC",
  "Disney",
  "DOTS",
  "DUPLO",
  "Friends",
  "Harry Potter",
  "Ideas",
  "Jurassic World",
  "LEGO Animal Crossing",
  "LEGO DREAMZzz",
  "LEGO Education",
  "LEGO La Casa de Muñecas de Gabby",
  "LEGO Icons",
  "LEGO Indiana Jones",
  "LEGO Super Mario",
  "Lord of the Rings",
  "Marvel",
  "Minecraft",
  "Minifiguras",
  "Monkie Kid",
  "NINJAGO",
  "Powered Up",
  "SERIOUS PLAY",
  "Sonic the Hedgehog",
  "Speed Champions",
  "Spider-Man",
  "Star Wars",
  "Technic",
];

export const subComprarPrecios = [
  "VER TODOS LOS RANGOS DE PRECIOS",
  "Menos de 20 €",
  "20 € - 50 €",
  "50 € - 100 €",
  "100 € - 200 €",
  "Más de 200 €",
];
export const subComprarArticulos = [
  "VER TODOS LOS ARTÍCULOS LEGO",
  "Accesorios",
  "Mochilas",
  "Libros",
  "Ropa",
  "Llaveros",
  "Fiambreras",
  "Juguetes de peluche",
  "Puzles y juegos de mesa",
  "Juegos de rol y vestimentas",
  "Artículos de papelería",
  "Almacenamiento",
  "Botellas de agua LEGO",
];
export const subComprarIntereses = [
  "VER TODOS LOS INTERESES",
  "Para fans adultos",
  "Animales",
  "Manualidades",
  "Edifiios",
  "Coches",
  "Programación para niños",
  "Dragones",
  "Fantasía",
  "Películas",
  "Videojuegos",
  "Aprender a construir",
  "Música",
  "Ninjas",
  "Preescolar",
  "Princesas",
  "Héroes del mundo real",
  "Robots para niños",
  "Festividades",
  "Espacio",
  "Deportes",
  "STEM",
  "Trenes",
  "Viajes",
  "Series de televisión",
  "Vehículos",
];
export const subComprarPickBuild = [
  "PICK AND BUILD",
  "Pick a Brick",
  "Accesorios y kits de ladrillos",
];
export const subDescubirValores = [
  "The LEGO Group",
  "Noticias LEGO",
  "Sostenibilidad",
];
export const subDescubirApps = ["LEGO Builder", "App LEGO Life"];
export const subDescubrirRevistas = ["Catálogos LEGO"];

export const subComprarEdades = [
  { id: "edades", texto: "VER TODAS LAS EDADES" },
  { id: "rangoPrecios", texto: "1,5+" },
  { id: "articulosLEGO", texto: "4+" },
  { id: "intereses", texto: "6+" },
  { id: "pickBuild", texto: "9+" },
  { id: "edades", texto: "13+" },
  { id: "edades", texto: "18+" },
];
